name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REPOSITORY_NAME: ${{ github.event.repository.name }} # GitHub仓库名

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # 将GitHub仓库名转换成小写，并设置镜像名称
    - name: Prepare the Docker image name
      run: echo "IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/${REPOSITORY_NAME,,}:latest" >> $GITHUB_ENV

    # 构建 Docker 镜像并打上相应标签
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag $IMAGE_NAME
      
    # 登录至 Docker Hub 
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    # 推送镜像至 Docker Hub
    - name: Push the Docker image
      run: docker push $IMAGE_NAME
